<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="fr_FR">
<context>
    <name>CTCron</name>
    <message>
        <location filename="../crontablib/ctcron.cpp" line="109"/>
        <source>No password entry found for uid &apos;%1&apos;</source>
        <translation>Pas de compte trouvé pour l'uid &quot;%1&quot;</translation>
    </message>
    <message>
        <location filename="../crontablib/ctcron.cpp" line="246"/>
        <source>File generated by Crontablib the %1.</source>
        <comment>Generation Message + current date</comment>
        <translation>Fichier généré par Crontablib le %1.</translation>
    </message>
    <message>
        <location filename="../crontablib/ctcron.cpp" line="286"/>
        <source>&lt;em&gt;No output.&lt;/em&gt;</source>
        <translation>&lt;em&gt;Aucune sortie.&lt;/em&gt;</translation>
    </message>
    <message>
        <location filename="../crontablib/ctcron.cpp" line="292"/>
        <source>&lt;em&gt;No error.&lt;/em&gt;</source>
        <translation>&lt;em&gt;Aucune erreur.&lt;/em&gt;</translation>
    </message>
    <message>
        <location filename="../crontablib/ctcron.cpp" line="298"/>
        <source>&lt;p&gt;&lt;strong&gt;Command:&lt;/strong&gt; %1&lt;/p&gt;&lt;strong&gt;Command could not be started&lt;/strong&gt;</source>
        <translation>&lt;p&gt;&lt;strong&gt;Commande :&lt;/strong&gt; %1&lt;/p&gt;&lt;strong&gt;La commande n'a pu être exécutée&lt;/strong&gt;</translation>
    </message>
    <message>
        <location filename="../crontablib/ctcron.cpp" line="302"/>
        <source>&lt;p&gt;&lt;strong&gt;Command:&lt;/strong&gt; %1&lt;/p&gt;&lt;strong&gt;Standard Output :&lt;/strong&gt;&lt;pre&gt;%2&lt;/pre&gt;&lt;strong&gt;Error Output :&lt;/strong&gt;&lt;pre&gt;%3&lt;/pre&gt;</source>
        <translation>&lt;p&gt;&lt;strong&gt;Commande :&lt;/strong&gt; %1&lt;/p&gt;&lt;strong&gt;Sortie standard:&lt;/strong&gt;&lt;pre&gt;%2&lt;/pre&gt;&lt;strong&gt;Sortie d'erreur :&lt;/strong&gt;&lt;pre&gt;%3&lt;/pre&gt;</translation>
    </message>
    <message>
        <location filename="../crontablib/ctcron.cpp" line="309"/>
        <source>An error occurred while updating crontab.</source>
        <translation>Une erreur est survenue en modifiant crontab.</translation>
    </message>
    <message>
        <location filename="../crontablib/ctcron.cpp" line="318"/>
        <source>Unable to open crontab file for writing</source>
        <translation>Impossible d'ouvrir le fichier crontab en écriture</translation>
    </message>
    <message>
        <location filename="../crontablib/ctcron.cpp" line="319"/>
        <source>The file %1 could not be opened.</source>
        <translation>Le fichier %1 n'a pu être ouvert.</translation>
    </message>
</context>
<context>
    <name>CTDayOfMonth</name>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="22"/>
        <source>every day </source>
        <translation>tous les jours </translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>1st</source>
        <translation>1er</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>2nd</source>
        <translation>2ème</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>3rd</source>
        <translation>3ème</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>4th</source>
        <translation>4ème</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>5th</source>
        <translation>5ème</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>6th</source>
        <translation>6ème</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>7th</source>
        <translation>7ème</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>8th</source>
        <translation>8ème</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>9th</source>
        <translation>9ème</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>10th</source>
        <translation>10ème</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>11th</source>
        <translation>11ème</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>12th</source>
        <translation>12ème</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>13th</source>
        <translation>13ème</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>14th</source>
        <translation>14ème</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>15th</source>
        <translation>15ème</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>16th</source>
        <translation>16ème</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="32"/>
        <source>17th</source>
        <translation>17ème</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>18th</source>
        <translation>18ème</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>19th</source>
        <translation>19ème</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>20th</source>
        <translation>20ème</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>21st</source>
        <translation>21ème</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>22nd</source>
        <translation>22ème</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>23rd</source>
        <translation>23ème</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>24th</source>
        <translation>24ème</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>25th</source>
        <translation>25ème</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>26th</source>
        <translation>26ème</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>27th</source>
        <translation>27ème</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>28th</source>
        <translation>28ème</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>29th</source>
        <translation>29ème</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>30th</source>
        <translation>30ème</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdom.cpp" line="33"/>
        <source>31st</source>
        <translation>31ème</translation>
    </message>
</context>
<context>
    <name>CTDayOfWeek</name>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="43"/>
        <source>every day </source>
        <translation>tous les jours </translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="55"/>
        <source>Mon</source>
        <translation>Lun</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="55"/>
        <source>Tue</source>
        <translation>Mar</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="55"/>
        <source>Wed</source>
        <translation>Mer</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="55"/>
        <source>Thu</source>
        <translation>Jeu</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="55"/>
        <source>Fri</source>
        <translation>Ven</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="55"/>
        <source>Sat</source>
        <translation>Sam</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="55"/>
        <source>Sun</source>
        <translation>Dim</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="57"/>
        <source>Monday</source>
        <translation>Lundi</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="57"/>
        <source>Tuesday</source>
        <translation>Mardi</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="57"/>
        <source>Wednesday</source>
        <translation>Mercredi</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="57"/>
        <source>Thursday</source>
        <translation>Jeudi</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="57"/>
        <source>Friday</source>
        <translation>Vendredi</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="57"/>
        <source>Saturday</source>
        <translation>Samedi</translation>
    </message>
    <message>
        <location filename="../crontablib/ctdow.cpp" line="57"/>
        <source>Sunday</source>
        <translation>Dimanche</translation>
    </message>
</context>
<context>
    <name>CTGlobalCron</name>
    <message>
        <location filename="../crontablib/ctGlobalCron.cpp" line="28"/>
        <source>All users</source>
        <translation>Tous les utilisateurs</translation>
    </message>
</context>
<context>
    <name>CTHost</name>
    <message>
        <location filename="../crontablib/cthost.cpp" line="59"/>
        <source>You have been blocked from using Crontablib                          by either the /etc/cron.allow file or the /etc/cron.deny file.                          

Check the crontab man page for further details.</source>
        <translation>Vous n'avez pas la permission d'utiliser Crontablib            selon le fichier /etc/cron.allow ou /etc/cron.deny.                          

Consultez la page de manuel de crontab pour plus d'informations.</translation>
    </message>
    <message>
        <location filename="../crontablib/cthost.cpp" line="141"/>
        <source>User %1: %2</source>
        <comment>User login: errorMessage</comment>
        <translation>Utilisateur %1: %2</translation>
    </message>
</context>
<context>
    <name>CTMonth</name>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="22"/>
        <source>every month</source>
        <translation>tous les mois</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>January</source>
        <translation>Janvier</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>February</source>
        <translation>Février</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>March</source>
        <translation>Mars</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>April</source>
        <translation>Avril</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>May</source>
        <comment>May long</comment>
        <translation>Mai</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>June</source>
        <translation>Juin</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>July</source>
        <comment>July long</comment>
        <translation>Juillet</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>August</source>
        <translation>Août</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>September</source>
        <translation>Septembre</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>October</source>
        <translation>Octobre</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>November</source>
        <translation>Novembre</translation>
    </message>
    <message>
        <location filename="../crontablib/ctmonth.cpp" line="32"/>
        <source>December</source>
        <translation>Décembre</translation>
    </message>
</context>
<context>
    <name>CTSystemCron</name>
    <message>
        <location filename="../crontablib/ctSystemCron.cpp" line="45"/>
        <source>System Crontab</source>
        <translation>Crontab système</translation>
    </message>
</context>
<context>
    <name>CTTask</name>
    <message>
        <location filename="../crontablib/cttask.cpp" line="232"/>
        <source>at system startup</source>
        <translation>au démarrage du système</translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="239"/>
        <source>%1, %2</source>
        <comment>1:Time Description, 2:Date Description</comment>
        <translation>%1, %2</translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="244"/>
        <source>every %1</source>
        <comment>Every &apos;days of week&apos;</comment>
        <translation>tous les %1</translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="248"/>
        <source>%1 of %2</source>
        <comment>&apos;Days of month&apos; of &apos;Months&apos;</comment>
        <translation>le %1 de %2</translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="261"/>
        <source>every day </source>
        <translation>tous les jours </translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="272"/>
        <source>%1 as well as %2</source>
        <comment>1:Day of month, 2:Day of week</comment>
        <translation>%1 et %2</translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="304"/>
        <source>%1:%2</source>
        <comment>1:Hour, 2:Minute</comment>
        <translation>%1:%2</translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="314"/>
        <source>, and </source>
        <translation>, et </translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="316"/>
        <source> and </source>
        <translation> et </translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="319"/>
        <source>, </source>
        <translation>, </translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="325"/>
        <source>at %1</source>
        <comment>Hour::Minute list</comment>
        <translation>%1</translation>
    </message>
    <message>
        <location filename="../crontablib/cttask.cpp" line="332"/>
        <source>Every minute</source>
        <comment>Every minute</comment>
        <translation>Toutes les minutes</translation>
    </message>
</context>
<context>
    <name>CTUnit</name>
    <message>
        <location filename="../crontablib/ctunit.cpp" line="170"/>
        <source>,</source>
        <translation>,</translation>
    </message>
    <message>
        <location filename="../crontablib/ctunit.cpp" line="171"/>
        <source> and </source>
        <translation> et </translation>
    </message>
    <message>
        <location filename="../crontablib/ctunit.cpp" line="174"/>
        <source>, </source>
        <translation>, </translation>
    </message>
</context>
<context>
    <name>CTVariable</name>
    <message>
        <location filename="../crontablib/ctvariable.cpp" line="121"/>
        <source>Override default home folder.</source>
        <translation>Forcer le répertoire utilisateur par défaut.</translation>
    </message>
    <message>
        <location filename="../crontablib/ctvariable.cpp" line="124"/>
        <source>Email output to specified account.</source>
        <translation>Envoyer un e-mail au compte spécifié.</translation>
    </message>
    <message>
        <location filename="../crontablib/ctvariable.cpp" line="127"/>
        <source>Override default shell.</source>
        <translation>Forcer le shell par défaut.</translation>
    </message>
    <message>
        <location filename="../crontablib/ctvariable.cpp" line="130"/>
        <source>Folders to search for program files.</source>
        <translation>Répertoires où chercher les fichiers de programme.</translation>
    </message>
    <message>
        <location filename="../crontablib/ctvariable.cpp" line="133"/>
        <source>Dynamic libraries location.</source>
        <translation>Emplacement des bibliothèques dynamiques.</translation>
    </message>
    <message>
        <location filename="../crontablib/ctvariable.cpp" line="136"/>
        <source>Local Variable</source>
        <translation>Variable locale</translation>
    </message>
</context>
</TS>
